networks:
  main-network:
    external: true
volumes:
  newdata:
services:
  mongo:
    image: mongo:6.0-jammy
    restart: unless-stopped
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - newdata:/data/db
    networks:
      - main-network
  web:
    build:
      context: .
    image: virtual-power-plant
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_DATABASE=test
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/test
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - main-network
